SCR_MissionHeader : "{886836A3B32E997B}Missions/Biryuk/TvT_Base.conf" {
 World "{6AF1CBF56B5AA616}Worlds/Biryuk/Takistan/Mulladdost.ent"
 m_sName "Пафос в Мулладосте"
 m_sPath ""
 m_sDescription "Опять штурмуем кишлак"
}