SCR_MissionHeader {
 World "{A15F5DE50897B266}Worlds/Gidra/Zarichne/TvT_Rembaza_Zarichne/TvT_Rembaza_Zarichne.ent"
 m_sName "Рембаза"
 m_sAuthor "Gidra"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}