SCR_MissionHeader {
 World "{DF63495E5C2E003D}Worlds/Gubastus/TvT_DeathFlowers_Galicia/TvT_DeathFlowers_Galicia.ent"
 m_sName "Цветки смерти"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}